### ISSUE TITLE
Allow mods to set custom translations

### ISSUE THREAD

**Issue by potatomon** [Snooful/Snooful#29]
Maybe add a `translate` command for moderators to set up custom translated messages for each command? For example:
 
     !translate flip "Bleblebleblebleh (heads). Blablablablah lol!"

**Comment by haykam821** [comment]
I am not planning on adding custom localizations; they should be contributed through a pull request.

I will be writing tests for localization completeness soon, but for now here are the percentages:

* `en-US`: 100% (obviously)
* `es-ES`: 21%
* `pt-BR`: 27%

**Comment by potatomon** [comment]
Oky, I'll see what I can do.

**Comment by haykam821** [comment]
I'm closing this because I am not planning on implementing this, but I did add localization completeness tests in #31. Spanish localizations were also updated recently in #34 but some for newer features are missing.

**Comment by haykam821** [comment]
Additionally, this would require rewriting a lot of code and localizations to use named placeholders rather than inferred or index-based ones, as most localizations do:

https://github.com/Snooful/Snooful/blob/4db6e0dcb6cd609823f9ff1dfb7f3e7ebe7f487e/src/locales.json#L104

https://github.com/Snooful/Snooful/blob/4db6e0dcb6cd609823f9ff1dfb7f3e7ebe7f487e/src/commands/emoji/emojiinfo.js#L37
